### ISSUE TITLE
CCTC开源

### ISSUE THREAD

**Issue by boxiaowave** [destwang/CTCResources#2]
你好！

非常感谢贵司在coling 2022上收集并计划开源CCTC数据集，请问这个数据集大致什么时候会发布呢？

**Comment by destwang** [comment]
数据集会在10月中旬放出，谢谢！

**Comment by boxiaowave** [comment]
好的，感谢

**Comment by boxiaowave** [comment]
请问下这个数据集还打算开源吗？

**Comment by destwang** [comment]
不好意思，数据明天放出，谢谢！

**Comment by HuangWenXin223** [comment]
请问CCTC数据集还没有开源么。我找不到在哪儿

**Comment by destwang** [comment]
> 请问CCTC数据集还没有开源么。我找不到在哪儿

https://pan.baidu.com/s/1FzWzlshVWBVqZvLt07zqiQ
password: 45ok
